name: On Extension Update
on:
  push:
    branches:
      - 'release/**'
    paths:
      - 'extensions/agent/package.json'

jobs:
  update-extensions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: release/extensions
    - run: wget https://raw.githubusercontent.com/microsoft/azuredatastudio/master/extensions/agent/package.json
    - run: git add -A
    - run: git commit -m "Update Agent version"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:

