name: On Extension Update
on:
  push:
    branches:
      - 'release/**'
    paths:
      - 'extensions/**/package.json'

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: ""
        destination_branch: "release/extensions"
        pr_title: "Pulling ${{ github.ref }} into release/extensions"
        pr_body: ":crown: *An automated PR*"
        pr_reviewer: "adbist"
        pr_assignee: "adbist"
        pr_label: "auto-pr"
        pr_draft: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
