name: On Extension Update
on:
  push:
    branches:
      - 'release/**'
    paths:
      - 'extensions/agent/package.json'

jobs:
  update-extensions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: release/extensions
    - run: wget https://raw.githubusercontent.com/microsoft/azuredatastudio/master/extensions/agent/package.json
    - run: git add -A
    - name: Commit Files
      run: |
        git config --local user.email "adbist@microsoft.com"
        git config --local user.name "Aditya Bist"
        git commit -m "Update Agent version"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

