name: On Extension Update
on:
  push:
    branches:
      - 'release/**'
    paths:
      - 'extensions/agent/package.json'

jobs:
  update-extensions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: release/extensions
    - uses: actions/checkout@v2
      with:
        ref: master -- ../../extensions/agent/package.json
    - name: Update Agent
      run: git commit -m "Update Agent version"
      run: git push
