name: On Extension Update
on:
  push:
    branches:
      - 'release/**'
    paths:
      - 'extensions/agent/package.json'

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: Fetch resources
      run: ./scripts/fetch-resources.sh
    - name: Update files
      uses: alexesprit/action-update-file@master
      with:
        file-path: ../../extensions/agent/package.json
        branch: 'release/extensions'
        commit-msg: Update Agent version
        github-token: ${{ secrets.GITHUB_TOKEN }}
