name: On Extension Update
on:
  push:
    branches:
      - 'release/**'
    paths:
      - 'extensions/agent/package.json'

jobs:
  update-extensions:
    runs-on: ubuntu-latest
    steps:
    - run: git checkout release/extensions
    - run: git checkout master -- ../../extensions/agent/package.json
    - run: git commit -m "Update Agent version"
    - run: git push
